# Generated by Django 4.2.2 on 2026-06-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0002_alter_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
