# Generated by Django 4.2.2 on 2024-06-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0006_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
