# Generated by Django 4.2.2 on 2024-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0011_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='passwordHash',
            field=models.CharField(max_length=128),
        ),
    ]
